CREATE TABLE "repo"."table"(
    SO2 DOUBLE PRECISION,
    NO2 DOUBLE PRECISION,
    NO1 DOUBLE PRECISION,
    CO2 DOUBLE PRECISION,
    O3 DOUBLE PRECISION,
    PM10 DOUBLE PRECISION,
    BENZENE DOUBLE PRECISION,
    PM2_5 DOUBLE PRECISION
);
