CREATE TABLE "repo"."table"(
SO2 DOUBLE PRECISION,
NO2 DOUBLE PRECISION,
NO1 DOUBLE PRECISION,
CO2 DOUBLE PRECISION,
O3 DOUBLE PRECISION,
pm10 DOUBLE PRECISION,
benzene DOUBLE PRECISION,
pm2_5 DOUBLE PRECISION
);