CREATE TABLE "repo"."table"(
measure_date TIMESTAMP WITHOUT TIME ZONE,
measure_type VARCHAR,
SO2 DOUBLE PRECISION,
NO2 DOUBLE PRECISION,
NO1 DOUBLE PRECISION,
CO2 DOUBLE PRECISION,
O3 DOUBLE PRECISION,
pm10 DOUBLE PRECISION,
benzene DOUBLE PRECISION,
pm2_5 DOUBLE PRECISION,

PRIMARY KEY (measure_date,measure_type)
);
