name: Linting with flake8 and sqlfluff

on: [pull_request]

jobs:
  lint-flake8-sqlfluff:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
      - name: Install SQLFluff
        run: "pip install sqlfluff==0.3.6"
      - name: Lint SQL files
        run: "sqlfluff lint ./bitdotio"